version: '3.9'

services:
  api:
    image: denizsonmez/myrepository:latest
    container_name: app
    environment:
        CONNECTION_STR: jdbc:postgresql://db:5432
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
        DEPLOYED: true
        SECRET_KEY: ABAn73oTCLEUVW3eX3UNMohoOlSzmel2Aa34eiVZ7lA=
        TOKEN_EXPIRE_TIME: 1800000
        ISSUER: ds.com
    ports:
      - "7070:7070"
    networks:
      - database_network

  db:
    image: postgres:15.3-alpine3.18
    container_name: db
    restart: unless-stopped
    networks:
      - database_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # init.sql is a file that is run when the container is created
    ports:
      - "5432:5432"

networks:
  database_network:
    name: database_network
    internal: false
    driver: bridge